
name: Weekly funding opportunity scraper and Email Sender

on:
  schedule:
    # Runs at 9:00 AM ET (14:00 UTC) every Monday
    - cron: '0 14 * * 1'

  workflow_dispatch: # Allows manual triggering

jobs:
  run-scraper-and-send-email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Step 4: Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Run the scraper Python script using Poetry
      - name: Run the scraper script
        run: |
          poetry run python funding_opportunity/grants_gov_scraper.py

      # Step 6: Create token.json from GitHub Secret
      - name: Create token.json
        run: |
          echo "$GMAIL_TOKEN_JSON" > funding_opportunity/token.json
        env:
          GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}

      # Step 7: Run the email-sending Python script using Poetry
      - name: Run weekly email script
        run: |
          poetry run python funding_opportunity/send_email.py
